[DockerLogInput]
  endpoint = 'unix:///var/run/docker.sock'
  decoder = 'MultiDecoder'

[MultiDecoder]
  cascade_strategy = 'first-wins'
  subs = [
    'NginxAccess',
    'NginxError',
    'PayloadRegexDecoder',
  ]

[NginxAccess]
  type = 'SandboxDecoder'
  filename = 'lua_decoders/nginx_access.lua'
  [NginxAccess.config]
    type = 'nginx.access'
    user_agent_transform = true
    log_format = "$remote_addr - $remote_user [$msec] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""

[NginxError]
  type = 'SandboxDecoder'
  filename = 'lua_decoders/nginx_error.lua'
  [NginxError.config]
    type = 'nginx.error'

[PayloadRegexDecoder]
  match_regex = '(...)'
  [PayloadRegexDecoder.message_fields]
    Type = "LogNotManaged"
