[InfluxSchema]
  type = 'SandboxEncoder'
  filename = 'lua_encoders/schema_influx.lua'
  [InfluxSchema.config]
    exclude_base_fields = true
    #skip_fields = ''
    series = "%{Type}"

[InfluxOutput]
  type = 'HttpOutput'
  encoder = 'InfluxSchema'
  message_matcher = 'Type == "nginx.access"'
  address = 'http://influxdb.default.svc.cluster.local/db/logs/series'
  method = 'POST'
  username = 'root'
  password = 'root'
