[InfluxSchema]
  type = 'SandboxEncoder'
  filename = 'lua_encoders/schema_influx.lua'
  [InfluxSchema.config]
    series = "heka.%{Logger}"

[InfluxOutput]
  type = 'HttpOutput'
  encoder = 'InfluxSchema'
  message_matcher = 'Type == "nginx.access"'
  address = 'http://influxdb.default.svc.cluster.local/db/heka/series'
  method = 'POST'
  username = 'root'
  password = 'root'

[PayloadEncoder]

[LogOutput]
  encoder = 'PayloadEncoder'
  message_matcher = 'Type == "nginx.access"'

[DashboardOutput]
  ticker_interval = 1
